name: CI - Build and Test
on:
  push:
    branches:
      - main
      - releases/*
    pull_request:
      - releases/*

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Configure .net env
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'
      
      - name: Restore dependencies
        run: dotnet restore BaseUtils.sln

      - name: Run tests
        run: dotnet test --verbosity quiet /p:CollectCoverage=true /p:Threshold=100